# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'  # You can choose a different agent if required.

steps:
  - script: |
      git clone --mirror $(Build.Repository.Uri)
      cd $(Build.Repository.Name).git
      git remote set-url --push origin $(github_repo_url)
      git fetch -p origin
      git push --mirror
    displayName: 'Sync to GitHub'