# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Build has started!
  displayName: 'Start building Solution'

- script: dotnet build 'SearchTheWebServer/*.csproj'
  displayName: 'Building SearchTheWebServer project'
   
- script: 'dotnet build SearchTheWeb'
  displayName: 'Building SearchTheWeb project'